language: go

go:
- 1.4
- 1.4.1
- 1.4.2
- 1.5
- 1.5.1

before_install:
- export PATH=$HOME/gopath/bin:$PWD/Godeps/_workspace/bin:$PATH
- export GOPATH=$PWD/Godeps/_workspace:$GOPATH

install:
# Prevent default install task that does a `go get -t ./...`
- true

script:
- go test -v $(go list ./... | grep -v /ci/)
